IF COL_LENGTH('BEXPORT_LC_DOCS_PROCESSING', 'IssuingBankName') IS NULL
BEGIN
    ALTER TABLE BEXPORT_LC_DOCS_PROCESSING
    ADD IssuingBankName nvarchar(250) null;
		
END
ELSE
BEGIN
	ALTER TABLE BEXPORT_LC_DOCS_PROCESSING
    ALTER COLUMN IssuingBankName nvarchar(250) null;
END

GO

IF COL_LENGTH('BEXPORT_LC_DOCS_PROCESSING', 'AcceptRemarks') IS NULL
BEGIN
    ALTER TABLE BEXPORT_LC_DOCS_PROCESSING
    ADD AcceptRemarks nvarchar(100) null;
		
END
ELSE
BEGIN
	ALTER TABLE BEXPORT_LC_DOCS_PROCESSING
    ALTER COLUMN AcceptRemarks nvarchar(100) null;
END

GO

IF COL_LENGTH('BEXPORT_DOCS_PROCESSING_SETTLEMENT', 'NostroAccount') IS NULL
BEGIN
    ALTER TABLE BEXPORT_DOCS_PROCESSING_SETTLEMENT
    ADD NostroAccount varchar(250) null;
		
END

IF COL_LENGTH('BEXPORT_LC_DOCS_PROCESSING_CHARGES', 'TabId') IS NULL
BEGIN
    ALTER TABLE BEXPORT_LC_DOCS_PROCESSING_CHARGES
    ADD TabId int  null;
		
END

IF EXISTS(SELECT * FROM sys.key_constraints WHERE NAME = 'PK_BEXPORT_LC_DOCS_PROCESSING_CHARGES')
BEGIN
	ALTER TABLE BEXPORT_LC_DOCS_PROCESSING_CHARGES
	DROP CONSTRAINT PK_BEXPORT_LC_DOCS_PROCESSING_CHARGES; 
END
GO




